use_columns: 
  - FISCAL_YR
  - FISCAL_MTH
  - DEPT_NAME
  - DIV_NAME
  - MERCHANT
  - CAT_DESC
  - TRANS_DT
  - AMT
  - DayOfWeek
  - isWeekday

date_column:
  - TRANS_DT

text_column:
  - DEPT_NAME
  - DIV_NAME
  - MERCHANT
  - CAT_DESC

int_column:
 - FISCAL_YR
 - FISCAL_MTH

float_column:
  - AMT